services:
  postgis:
    image: postgis/postgis
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: seba0708
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
